spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ide
    username: ide
    password: ide321
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      'hibernate.format_sql': true
  flyway:
    enabled: true
    baseline-on-migrate: true
    url: jdbc:mysql://localhost:3306/ide
    user: ide
    password: ide321

logging:
  level:
    'org.hibernate.SQL': debug
    'org.hibernate.type': trace
