spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/back
    username: root
    password: root
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      .hibernate.temp.use_jdbc_metadata_defaults: false
      'hibernate.format_sql': true
      .hibernate.dialect: org.hibernate.dialect.MySQLDialect

  flyway:
    locations: classpath:/db/migration
    enabled: true
    baseline-on-migrate: true
    url: jdbc:mysql://localhost:3306/back
    user: root
    password: root

logging:
  level:
    'org.hibernate.SQL': debug
    'org.hibernate.type': trace

jwt:
  secret: secretKey1234511222222222222222222222222222222222222222222222222222222222222
  access-exp: 3600000
  refresh-exp: 3600000
